# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false # FIXME

formats:
- pdf
- epub

python:
  install:
  - requirements: requirements-dev.txt
  - method: pip
    path: .
