mysql:
    image: mysql:5.7
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
        - 3306:3306
    volumes:
        - /tmp/aiomysql/:/var/run/mysqld/
        - ./.docker/:/docker-entrypoint-initdb.d/
        - ./.docker/my.cnf:/etc/my.cnf
